version: '3'

services:
  db:
    image: postgres:13.6
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:${DB_PORT}
  redis:
    image: redis:7.0-rc3-alpine3.15
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  auth:
    build: .
    entrypoint: >
      sh -c "python -m pytest -W ignore tests/
             flask db upgrade
             flask createsuperuser admin password123
             gunicorn wsgi_app:app --bind :5000"
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
